import { useEffect, useRef, useState } from "react";
import { X } from "lucide-react";

type Props = { file: File; onCancel: () => void; onComplete: (file: File) => void };

/** Local, dependency-free 4:5 cropper. Output is always an optimized WebP. */
export function ImageCropDialog({ file, onCancel, onComplete }: Props) {
  const [zoom, setZoom] = useState(1); const [offsetX, setOffsetX] = useState(0); const [offsetY, setOffsetY] = useState(0);
  const source = useRef<HTMLImageElement | null>(null); const [url, setUrl] = useState("");
  useEffect(() => { const next = URL.createObjectURL(file); setUrl(next); return () => URL.revokeObjectURL(next); }, [file]);
  function save() { const image = source.current; if (!image) return; const canvas = document.createElement("canvas"); canvas.width = 1200; canvas.height = 1500; const ctx = canvas.getContext("2d"); if (!ctx) return; const scale = Math.max(canvas.width / image.naturalWidth, canvas.height / image.naturalHeight) * zoom; const width = image.naturalWidth * scale; const height = image.naturalHeight * scale; ctx.drawImage(image, (canvas.width - width) / 2 + offsetX * canvas.width, (canvas.height - height) / 2 + offsetY * canvas.height, width, height); canvas.toBlob((blob) => { if (blob) onComplete(new File([blob], `${file.name.replace(/\.[^.]+$/, "")}.webp`, { type: "image/webp" })); }, "image/webp", .86); }
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-ink/80 p-4"><div className="w-full max-w-lg bg-background p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="eyebrow">Image crop</p><h2 className="font-display text-2xl">Set the 4:5 frame</h2></div><button aria-label="Cancel" onClick={onCancel}><X className="size-5" /></button></div><div className="relative mx-auto mt-5 aspect-[4/5] max-h-[52vh] overflow-hidden bg-muted"><img ref={source} src={url} alt="Crop preview" className="h-full w-full object-cover" style={{ transform: `scale(${zoom}) translate(${offsetX * 100}%, ${offsetY * 100}%)` }} /></div><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><label>Zoom<input aria-label="Zoom" type="range" min="1" max="2.5" step=".01" value={zoom} onChange={(e) => setZoom(Number(e.target.value))} className="mt-2 w-full" /></label><label>Horizontal<input aria-label="Horizontal position" type="range" min="-.5" max=".5" step=".01" value={offsetX} onChange={(e) => setOffsetX(Number(e.target.value))} className="mt-2 w-full" /></label><label>Vertical<input aria-label="Vertical position" type="range" min="-.5" max=".5" step=".01" value={offsetY} onChange={(e) => setOffsetY(Number(e.target.value))} className="mt-2 w-full" /></label></div><button onClick={save} className="mt-6 w-full bg-foreground px-5 py-3 text-[.7rem] uppercase tracking-[.16em] text-background">Use cropped WebP</button></div></div>;
}
